### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by farouk26** [farouk26/Echo-Movie-Platform#2]
### Description
Create a landing page component that contains a hero section, a button that takes the user to the homepage and a FAQs section. The landing page should be attractive and informative, and match the theme of the movie platform.

**Subtasks**

- [ ] Choose a suitable background image and a catchy slogan for the hero section
- [ ] Add a button that links to the homepage of the movie platform
- [ ] Write the FAQs and display them
- [ ] Test the landing page on different screen sizes and browsers
