### ISSUE TITLE
 Footer

### ISSUE THREAD

**Issue by farouk26** [farouk26/Echo-Movie-Platform#3]
### Description
Create a footer component that contains the movie platform Logo, some useful links and a social media icons. The footer should be simple and consistent with the rest of the website.

**Subtasks**

- [x] Write the footer content and style it
- [x] Add links to the useful pages and the social media accounts
- [ ] Test the footer on different screen sizes and browsers
